package _ServerPackage;


/**
* _ServerPackage/Common_IntefacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/CommonDirectory/New/Assignment2/6231_Assignment-2/src/Common_Interface.idl
* Friday, June 28, 2019 5:53:20 PM EDT
*/

public abstract class Common_IntefacePOA extends org.omg.PortableServer.Servant
 implements _ServerPackage.Common_IntefaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  /** The methods. */
  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getBookingSchedule", new java.lang.Integer (0));
    _methods.put ("bookEvent", new java.lang.Integer (1));
    _methods.put ("cancelEvent", new java.lang.Integer (2));
    _methods.put ("addEvent", new java.lang.Integer (3));
    _methods.put ("removeEvent", new java.lang.Integer (4));
    _methods.put ("listEventAvailability", new java.lang.Integer (5));
    _methods.put ("swapEvent", new java.lang.Integer (6));
  }

  /* (non-Javadoc)
   * @see org.omg.CORBA.portable.InvokeHandler#_invoke(java.lang.String, org.omg.CORBA.portable.InputStream, org.omg.CORBA.portable.ResponseHandler)
   */
  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // _ServerPackage/Common_Inteface/getBookingSchedule
       {
         String customerID = in.read_string ();
         String $result = null;
         $result = this.getBookingSchedule (customerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // _ServerPackage/Common_Inteface/bookEvent
       {
         String customerID = in.read_string ();
         String eventID = in.read_string ();
         String eventType = in.read_string ();
         String $result = null;
         $result = this.bookEvent (customerID, eventID, eventType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // _ServerPackage/Common_Inteface/cancelEvent
       {
         String customerID = in.read_string ();
         String eventID = in.read_string ();
         String eventType = in.read_string ();
         String $result = null;
         $result = this.cancelEvent (customerID, eventID, eventType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // _ServerPackage/Common_Inteface/addEvent
       {
         String eventID = in.read_string ();
         String eventType = in.read_string ();
         String bookingCapacity = in.read_string ();
         String $result = null;
         $result = this.addEvent (eventID, eventType, bookingCapacity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // _ServerPackage/Common_Inteface/removeEvent
       {
         String eventID = in.read_string ();
         String eventType = in.read_string ();
         String $result = null;
         $result = this.removeEvent (eventID, eventType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // _ServerPackage/Common_Inteface/listEventAvailability
       {
         String eventType = in.read_string ();
         String $result = null;
         $result = this.listEventAvailability (eventType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // _ServerPackage/Common_Inteface/swapEvent
       {
         String customerID = in.read_string ();
         String oldEventType = in.read_string ();
         String oldEventID = in.read_string ();
         String newEventType = in.read_string ();
         String newEventID = in.read_string ();
         String $result = null;
         $result = this.swapEvent (customerID, oldEventType, oldEventID, newEventType, newEventID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  /** The ids. */
  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ServerPackage/Common_Inteface:1.0"};

  /* (non-Javadoc)
   * @see org.omg.PortableServer.Servant#_all_interfaces(org.omg.PortableServer.POA, byte[])
   */
  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  /**
	 * This.
	 *
	 * @return the common inteface
	 */
  public Common_Inteface _this() 
  {
    return Common_IntefaceHelper.narrow(
    super._this_object());
  }

  /**
	 * This.
	 *
	 * @param orb the orb
	 * @return the common inteface
	 */
  public Common_Inteface _this(org.omg.CORBA.ORB orb) 
  {
    return Common_IntefaceHelper.narrow(
    super._this_object(orb));
  }


} // class Common_IntefacePOA
