package _ServerPackage;


/**
* _ServerPackage/Common_Inteface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/CommonDirectory/New/Assignment2/6231_Assignment-2/src/Common_Interface.idl
* Friday, June 28, 2019 5:53:20 PM EDT
*/

public interface Common_Inteface extends Common_IntefaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Common_Inteface
