package _ServerPackage;


/**
* _ServerPackage/Common_IntefaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/CommonDirectory/New/Assignment2/6231_Assignment-2/src/Common_Interface.idl
* Friday, June 28, 2019 5:53:20 PM EDT
*/

public interface Common_IntefaceOperations 
{
  
  /**
	 * Gets the booking schedule.
	 *
	 * @param customerID the customer ID
	 * @return the booking schedule
	 */
  String getBookingSchedule (String customerID);
  
  /**
	 * Book event.
	 *
	 * @param customerID the customer ID
	 * @param eventID    the event ID
	 * @param eventType  the event type
	 * @return the string
	 */
  String bookEvent (String customerID, String eventID, String eventType);
  
  /**
	 * Cancel event.
	 *
	 * @param customerID the customer ID
	 * @param eventID    the event ID
	 * @param eventType  the event type
	 * @return the string
	 */
  String cancelEvent (String customerID, String eventID, String eventType);
  
  /**
	 * Adds the event.
	 *
	 * @param eventID         the event ID
	 * @param eventType       the event type
	 * @param bookingCapacity the booking capacity
	 * @return the string
	 */
  String addEvent (String eventID, String eventType, String bookingCapacity);
  
  /**
	 * Removes the event.
	 *
	 * @param eventID   the event ID
	 * @param eventType the event type
	 * @return the string
	 */
  String removeEvent (String eventID, String eventType);
  
  /**
	 * List event availability.
	 *
	 * @param eventType the event type
	 * @return the string
	 */
  String listEventAvailability (String eventType);
  
  /**
	 * Swap event.
	 *
	 * @param customerID   the customer ID
	 * @param oldEventType the old event type
	 * @param oldEventID   the old event ID
	 * @param newEventType the new event type
	 * @param newEventID   the new event ID
	 * @return the string
	 */
  String swapEvent (String customerID, String oldEventType, String oldEventID, String newEventType, String newEventID);
} // interface Common_IntefaceOperations
