package _ServerPackage;


/**
* _ServerPackage/Common_IntefaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/CommonDirectory/New/Assignment2/6231_Assignment-2/src/Common_Interface.idl
* Friday, June 28, 2019 5:53:20 PM EDT
*/

abstract public class Common_IntefaceHelper
{
  
  /** The id. */
  private static String  _id = "IDL:ServerPackage/Common_Inteface:1.0";

  /**
	 * Insert.
	 *
	 * @param a    the a
	 * @param that the that
	 */
  public static void insert (org.omg.CORBA.Any a, _ServerPackage.Common_Inteface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  /**
	 * Extract.
	 *
	 * @param a the a
	 * @return the server package. common inteface
	 */
  public static _ServerPackage.Common_Inteface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  /** The type code. */
  private static org.omg.CORBA.TypeCode __typeCode = null;
  
  /**
	 * Type.
	 *
	 * @return the org.omg. CORB a. type code
	 */
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (_ServerPackage.Common_IntefaceHelper.id (), "Common_Inteface");
    }
    return __typeCode;
  }

  /**
	 * Id.
	 *
	 * @return the string
	 */
  public static String id ()
  {
    return _id;
  }

  /**
	 * Read.
	 *
	 * @param istream the istream
	 * @return the server package. common inteface
	 */
  public static _ServerPackage.Common_Inteface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_Common_IntefaceStub.class));
  }

  /**
	 * Write.
	 *
	 * @param ostream the ostream
	 * @param value   the value
	 */
  public static void write (org.omg.CORBA.portable.OutputStream ostream, _ServerPackage.Common_Inteface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  /**
	 * Narrow.
	 *
	 * @param obj the obj
	 * @return the server package. common inteface
	 */
  public static _ServerPackage.Common_Inteface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof _ServerPackage.Common_Inteface)
      return (_ServerPackage.Common_Inteface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _ServerPackage._Common_IntefaceStub stub = new _ServerPackage._Common_IntefaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  /**
	 * Unchecked narrow.
	 *
	 * @param obj the obj
	 * @return the server package. common inteface
	 */
  public static _ServerPackage.Common_Inteface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof _ServerPackage.Common_Inteface)
      return (_ServerPackage.Common_Inteface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _ServerPackage._Common_IntefaceStub stub = new _ServerPackage._Common_IntefaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
