package _ServerPackage;

/**
* _ServerPackage/Common_IntefaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/CommonDirectory/New/Assignment2/6231_Assignment-2/src/Common_Interface.idl
* Friday, June 28, 2019 5:53:20 PM EDT
*/

public final class Common_IntefaceHolder implements org.omg.CORBA.portable.Streamable
{
  
  /** The value. */
  public _ServerPackage.Common_Inteface value = null;

  /**
	 * Instantiates a new common inteface holder.
	 */
  public Common_IntefaceHolder ()
  {
  }

  /**
	 * Instantiates a new common inteface holder.
	 *
	 * @param initialValue the initial value
	 */
  public Common_IntefaceHolder (_ServerPackage.Common_Inteface initialValue)
  {
    value = initialValue;
  }

  /* (non-Javadoc)
   * @see org.omg.CORBA.portable.Streamable#_read(org.omg.CORBA.portable.InputStream)
   */
  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = _ServerPackage.Common_IntefaceHelper.read (i);
  }

  /* (non-Javadoc)
   * @see org.omg.CORBA.portable.Streamable#_write(org.omg.CORBA.portable.OutputStream)
   */
  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    _ServerPackage.Common_IntefaceHelper.write (o, value);
  }

  /* (non-Javadoc)
   * @see org.omg.CORBA.portable.Streamable#_type()
   */
  public org.omg.CORBA.TypeCode _type ()
  {
    return _ServerPackage.Common_IntefaceHelper.type ();
  }

}
