package _ServerPackage;


/**
* _ServerPackage/Common_IntefaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/CommonDirectory/New/Assignment2/6231_Assignment-2/src/Common_Interface.idl
* Friday, June 28, 2019 5:53:20 PM EDT
*/

public interface Common_IntefaceOperations 
{
  String getBookingSchedule (String customerID);
  String bookEvent (String customerID, String eventID, String eventType);
  String cancelEvent (String customerID, String eventID, String eventType);
  String addEvent (String eventID, String eventType, String bookingCapacity);
  String removeEvent (String eventID, String eventType);
  String listEventAvailability (String eventType);
  String swapEvent (String customerID, String oldEventType, String oldEventID, String newEventType, String newEventID);
} // interface Common_IntefaceOperations
